export const ADD_ARTICLE = "ADD_ARTICLE"
export const REMOVE_ARTICLE = "REMOVE_ARTICLE"

export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE"

export const INVALID_ARTICLE = "INVALID_ARTICLE"
export const INVALID_ACTION = "INVALID_ACTION"

// Action types for artical api call 
export const FETCH_ARTICLE_PENDING = 'FETCH_ARTICLE_PENDING'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR'

// Action types for employee api call 
export const FETCH_EMPLOYEE_PENDING = 'FETCH_EMPLOYEE_PENDING'
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_ERROR = 'FETCH_EMPLOYEE_ERROR'

export const SAVE_EMPLOYEE_PENDING = 'SAVE_EMPLOYEE_PENDING'
export const SAVE_EMPLOYEE_SUCCESS = 'SAVE_EMPLOYEE_SUCCESS'
export const SAVE_EMPLOYEE_ERROR = 'SAVE_EMPLOYEE_ERROR'

export const DELETE_EMPLOYEE_PENDING = 'DELETE_EMPLOYEE_PENDING'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR'