// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_employee_management.Data;

#nullable disable

namespace dotnet_employee_management.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20241221025654_addProp")]
    partial class addProp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnet_employee_management.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhChiEm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanTocCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanTocMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiCuThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNhanGiayBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DiemKhuyenKhich")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMon1")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMon2")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMon3")
                        .HasColumnType("float");

                    b.Property<double?>("DiemTBCToanKhoa")
                        .HasColumnType("float");

                    b.Property<double?>("DiemXetTuyen")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiayKhen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HKTT_IDHuyen")
                        .HasColumnType("int");

                    b.Property<int?>("HKTT_IDTinh")
                        .HasColumnType("int");

                    b.Property<int?>("HKTT_PhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("HoDem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiLienLac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDDanToc")
                        .HasColumnType("int");

                    b.Property<string>("IDDoiTuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDKhuVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDLoaiSinhVien")
                        .HasColumnType("int");

                    b.Property<string>("IDNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDPhanLoaiTS")
                        .HasColumnType("int");

                    b.Property<string>("IDTruongLop12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("KhenThuongKyLuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoSo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaHoSo");

                    b.Property<int?>("NamTotNghiep")
                        .HasColumnType("int");

                    b.Property<string>("NgayCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinhCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinhMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayVaoDang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayVaoDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNghiepCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNghiepMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhapHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViecCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViecMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiThuongTruCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiThuongTruMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongThucTrungTuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhuongXa")
                        .HasColumnType("int");

                    b.Property<int?>("QuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("STT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STT");

                    b.Property<string>("SdtCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SdtLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SdtMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoBaoDanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SoBaoDanh");

                    b.Property<string>("SoCMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiaoCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiaoMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XepLoaiHanhKiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XepLoaiHocTap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admission");
                });

            modelBuilder.Entity("dotnet_employee_management.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDEMPLOYEE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("Age")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AGE");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("IdEmployee");

                    b.ToTable("EMPLOYEES");
                });

            modelBuilder.Entity("dotnet_employee_management.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("TOKEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TOKEN");

                    b.HasKey("ID");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
